### ISSUE TITLE
Erro no link

### ISSUE THREAD

**Issue by LockDzn** [PerfectDreams/VespertineBotList#5]
Quando você vai votar sem está logado... você autoriza a Gabriela, mas da erro:
![image](https://user-images.githubusercontent.com/28955729/45158891-b8122e00-b1bb-11e8-888f-39bec1578b08.png)

no link está: **https://bots.perfectdreams.net/id do bot/vote**
o certo seria: **https://bots.perfectdreams.net/bot/id do bot/vote**

**Comment by MrPowerGamerBR** [comment]
Corrigido em https://github.com/PerfectDreams/VespertineBotList/commit/176e741f8973b7c029856494ff82cc8f5e6be39d#diff-7680c7796320495236b763bcf27c00ddR65
